version: '3'
services:
  devcontainer:
    container_name: opengate-devcontainer
    # add groups from host for render, plugdev, video
    group_add:
      - '109' # render
      - '110' # render
      - '44' # video
      - '46' # plugdev
    shm_size: '256mb'
    #    network_mode: 'host'
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
      LIBVA_DRIVER_NAME: radeonsi
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/opengate:cached
      - ./web/dist:/opt/opengate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/opengate
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
