audio:
  enabled: false
birdseye:
  enabled: false
ffmpeg:
  retry_interval: 10
  hwaccel_args:
    - default
cameras:
  ip_camera_03:
    detect:
      fps: 5
      height: 480
      width: 640
    ffmpeg:
      inputs:
        - path: /media/opengate/thief.mp4
          roles:
            - detect
      input_args: -re -stream_loop -1 -fflags +genpts
    zones:
      all:
        coordinates: 640,480,640,0,0,0,0,480
        objects:
          - person
    mqtt:
      bounding_box: true
      crop: true
      enabled: true
      timestamp: true
      required_zones:
        - all
    onvif:
      autotracking:
        enabled: false
        zooming: disabled
        track:
          - person
        required_zones:
          - all
      host: 172.28.182.165
      port: 80
      username: admin
      password: ACLAB2023
      isapi_fallback: true
      isapi_sidecar:
        host: localhost
        port: 5600
logger:
  default: info
mqtt:
  enabled: true
  host: mosquitto.mqtt.ntranlab.com
  password: ctportal2024
  port: 8883
  topic_prefix: opengate/test-device-01
  user: admin
snapshots:
  enabled: true
  retain:
    default: 30
detectors:
  default:
    type: cpu
